// This just makes things look pretty
#ifndef GL_FUNCTION
#define GL_FUNCTION(type, name)
#include "GL/glext.h"
#endif

// Buffers
GL_FUNCTION(PFNGLGENBUFFERSPROC, glGenBuffers)
GL_FUNCTION(PFNGLDELETEBUFFERSPROC, glDeleteBuffers)
GL_FUNCTION(PFNGLBINDBUFFERPROC, glBindBuffer)
GL_FUNCTION(PFNGLBINDBUFFERBASEPROC, glBindBufferBase)
GL_FUNCTION(PFNGLBUFFERDATAPROC, glBufferData)
GL_FUNCTION(PFNGLNAMEDBUFFERDATAPROC, glNamedBufferData)
GL_FUNCTION(PFNGLBUFFERSUBDATAPROC, glBufferSubData)
GL_FUNCTION(PFNGLNAMEDBUFFERSUBDATAPROC, glNamedBufferSubData)
GL_FUNCTION(PFNGLGETBUFFERSUBDATAPROC, glGetBufferSubData)
GL_FUNCTION(PFNGLMAPBUFFERPROC, glMapBuffer)
GL_FUNCTION(PFNGLUNMAPBUFFERPROC, glUnmapBuffer)
GL_FUNCTION(PFNGLMAPNAMEDBUFFERPROC, glMapNamedBuffer)
GL_FUNCTION(PFNGLUNMAPNAMEDBUFFERPROC, glUnmapNamedBuffer)

// Vertex Arrays
GL_FUNCTION(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays)
GL_FUNCTION(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays)
GL_FUNCTION(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray)

// Programs
GL_FUNCTION(PFNGLCREATEPROGRAMPROC, glCreateProgram)
GL_FUNCTION(PFNGLDELETEPROGRAMPROC, glDeleteProgram)
GL_FUNCTION(PFNGLLINKPROGRAMPROC, glLinkProgram)
GL_FUNCTION(PFNGLUSEPROGRAMPROC, glUseProgram)
GL_FUNCTION(PFNGLDISPATCHCOMPUTEPROC, glDispatchCompute)
GL_FUNCTION(PFNGLGETPROGRAMIVPROC, glGetProgramiv)
GL_FUNCTION(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog)

// Shaders
GL_FUNCTION(PFNGLCREATESHADERPROC, glCreateShader)
GL_FUNCTION(PFNGLDELETESHADERPROC, glDeleteShader)
GL_FUNCTION(PFNGLSHADERSOURCEPROC, glShaderSource)
GL_FUNCTION(PFNGLCOMPILESHADERPROC, glCompileShader)
GL_FUNCTION(PFNGLATTACHSHADERPROC, glAttachShader)
GL_FUNCTION(PFNGLDETACHSHADERPROC, glDetachShader)
GL_FUNCTION(PFNGLGETSHADERIVPROC, glGetShaderiv)
GL_FUNCTION(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog)

// Attributes
GL_FUNCTION(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer)
GL_FUNCTION(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray)
GL_FUNCTION(PFNGLVERTEXATTRIBFORMATPROC, glVertexAttribFormat)
GL_FUNCTION(PFNGLVERTEXATTRIBIFORMATPROC, glVertexAttribIFormat)
GL_FUNCTION(PFNGLVERTEXATTRIBBINDINGPROC, glVertexAttribBinding)
GL_FUNCTION(PFNGLBINDVERTEXBUFFERPROC, glBindVertexBuffer)

// Uniforms
GL_FUNCTION(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation)
GL_FUNCTION(PFNGLUNIFORM3FPROC, glUniform3f)
GL_FUNCTION(PFNGLUNIFORM1IPROC, glUniform1i)
GL_FUNCTION(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv)

// Textures
GL_FUNCTION(PFNGLTEXSTORAGE3DPROC, glTexStorage3D)
GL_FUNCTION(PFNGLTEXIMAGE2DMULTISAMPLEPROC, glTexImage2DMultisample)
GL_FUNCTION(PFNGLGETTEXTURESUBIMAGEPROC, glGetTextureSubImage)

// Render Buffers
GL_FUNCTION(PFNGLGENRENDERBUFFERSPROC, glGenRenderbuffers)
GL_FUNCTION(PFNGLDELETERENDERBUFFERSPROC, glDeleteRenderbuffers)
GL_FUNCTION(PFNGLBINDRENDERBUFFERPROC, glBindRenderbuffer)
GL_FUNCTION(PFNGLRENDERBUFFERSTORAGEPROC, glRenderbufferStorage)
GL_FUNCTION(PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC, glRenderbufferStorageMultisample)

// Frame Buffers
GL_FUNCTION(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers)
GL_FUNCTION(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers)
GL_FUNCTION(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer)
GL_FUNCTION(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus)
GL_FUNCTION(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D)
GL_FUNCTION(PFNGLFRAMEBUFFERRENDERBUFFERPROC, glFramebufferRenderbuffer)
GL_FUNCTION(PFNGLBLITFRAMEBUFFERPROC, glBlitFramebuffer)
GL_FUNCTION(PFNGLDRAWBUFFERSPROC, glDrawBuffers)

// Other
GL_FUNCTION(PFNGLMEMORYBARRIERPROC, glMemoryBarrier)
GL_FUNCTION(PFNGLDEBUGMESSAGECALLBACKPROC, glDebugMessageCallback)
GL_FUNCTION(PFNGLBLENDEQUATIONSEPARATEPROC, glBlendEquationSeparate)
